# Generated by Django 4.2.5 on 2023-11-29 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('game', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('country_restriction', models.CharField(blank=True, max_length=50, null=True)),
                ('number_restriction', models.IntegerField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=20)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
